### ISSUE TITLE
No adaption to surrounding font size

### ISSUE THREAD

**Issue by mhchem** [cgnieder/chemgreek#1]
When using chemgreek in subscripts, the font size is wrong.

    \documentclass{article}
    \usepackage{textgreek}
    \usepackage{chemgreek}
    \begin{document}
    $\alpha\chemalpha H_{a\alpha\chemalpha{}a}$
    \end{document}

![image](https://cloud.githubusercontent.com/assets/16336692/12104381/2bd03890-b34b-11e5-9402-964da6a4abec.png)

**Comment by cgnieder** [comment]
Thanks. This is a problem of the textgreek mapping (and possibly others):

```latex
\documentclass{article}
\usepackage{textgreek,upgreek,amsmath}
\usepackage{chemgreek}

\newcommand*\test[1]{\selectchemgreekmapping{#1}$_{\printchemgreekalphabet}$\par}

\begin{document}
\test{default}
\test{textgreek}
\test{upgreek}

\textalpha$_{\text{\textalpha}}{}_{\mbox{\textalpha}}$

\end{document}```

I'll fix this soon.

**Comment by cgnieder** [comment]
The fix is on its way to CTAN :)
