### ISSUE TITLE
Undefined control sequence \prop_get:cV 

### ISSUE THREAD

**Issue by mhchem** [cgnieder/chemgreek#3]
\documentclass{article}
    \usepackage{chemgreek}
    \begin{document}
    \ExplSyntaxOn
    \chemgreek_get_from_mapping:nn { default } { Delta }
    \end{document}

produces the error

> ! Undefined control sequence.
> <argument> ...r_lower_case:f {Delta}}\prop_get:cV 
>                                                  {l__chemgreek_uppercase_ma...

**Comment by cgnieder** [comment]
Resolved with cset bd42658463228c646aab1d3d4d9b358e2e11d763
